# Generated by Django 5.1.4 on 2025-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_restrictedpage_options_post_access_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "type",
                    models.CharField(
                        choices=[("webinar", "Webinar"), ("workshop", "Taller")],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("public", "Público"), ("private", "Privado")],
                        default="public",
                        max_length=20,
                        verbose_name="tipo de acceso",
                    ),
                ),
                ("description", models.TextField(verbose_name="descripción")),
                ("event_time", models.DateTimeField(verbose_name="fecha y hora")),
                ("zoom_link", models.URLField(verbose_name="enlace de zoom")),
            ],
            options={
                "verbose_name": "Evento de Zoom",
                "verbose_name_plural": "Eventos de Zoom",
            },
        ),
    ]
