# Generated by Django 5.1.4 on 2025-02-05 15:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_zoomevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoomevent",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="zoom/events",
                validators=[blog.models.validate_image_size],
                verbose_name="imagen",
            ),
        ),
    ]
