# Generated by Django 5.1.4 on 2025-02-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_zoomevent_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
